### ISSUE TITLE
Using Speedy Mode?

### ISSUE THREAD

**Issue by JackCA** [dustinfarris/ember-glamor#3]
Does this work with [Glamor's speedy mode](https://github.com/threepointone/glamor#speedy-mode)? I'm new to glamor in general so I may be approaching this wrong, but I tried:
- importing `speedy` from `glamor` and running `speedy(true)` before I declared styles
- running `NODE_ENV=production ember s`

Both still appear to result in the non-speedy mode that writes to the style tag instead of using `insertRule`.

If this is an actual issue, then @dustinfarris if you can identify a path to a solution, I would volunteer to write the implementation.

**Comment by dustinfarris** [comment]
Hi @JackCA, thanks for reporting.

I have not attempted to enable speedy yet.  I think `speedy(true)` is the right way to do it, but probably needs to be in an initializer.

If you want to take a swing at it, I'd love to review a PR.

I would try creating an ember-glamor initializer that detects the current env and executes speedy appropriately.  e.g.:

```js
if (env.environment === 'production') {
  speedy(true);
} else {
  speedy(false);
}
```

We may want to add a config option as well so users can override and so we can test that it's working here in the addon as well.

Let me know if you plan to take this.  Thanks again.

**Comment by JackCA** [comment]
@dustinfarris writing the PR now and I can confirm that the initializer method works :)
